// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerKeeper.Infra.Data.Context;

namespace PowerKeeper.Infra.Data.Migrations
{
    [DbContext(typeof(PowerKeeperContext))]
    [Migration("20181219043947_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PowerKeeper.Domain.Models.Office", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("id")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("create_by")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnName("create_date");

                    b.Property<int>("DelFlag")
                        .HasColumnName("del_flag");

                    b.Property<string>("OfficeCode")
                        .HasColumnName("office_code")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnName("office_name")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OfficePhone")
                        .HasColumnName("office_phone")
                        .HasColumnType("varchar(64)");

                    b.Property<int>("OfficeType")
                        .HasColumnName("office_type");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("parent_id")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ParentIds")
                        .IsRequired()
                        .HasColumnName("parent_ids")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Remark")
                        .HasColumnName("remark")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("UpdateBy")
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("update_by")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnName("update_date");

                    b.HasKey("Id");

                    b.ToTable("sys_office");
                });
#pragma warning restore 612, 618
        }
    }
}
